language: nodejs
node_js:
  - "7"
before_script:
  - npm install

script:
  - npm run build

deploy:
  #- provider: pages
   # skip_cleanup: true
    #local_dir: docs/
    #github_token: $GITHUB_TOKEN
    #on:
    #  tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "kkiapay-‚*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: ["fiacre.ayedoun@gmail.com","boussarilatif1996@gmail.com"]
    api_key: $NPM_TOKEN
    on:
      tags: true
